 ---
title: "Initial Models Bayesian Project"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rethinking)
Data <- read.csv("merged.csv")
```



```{r}
twocities <- filter(Data, (city == "Berlin" | city == "Singapore"))

m1 <- map2stan(
  alist(
    price ~ dnorm(mu, sigma),
    mu <- alpha + alpha_city[city],
  alpha ~ dnorm(0, 200),
  alpha_city[city] ~ dnorm(0, sigma_city),
  sigma_city ~ dcauchy(0,5),
  sigma ~ dcauchy (0,5)
  ),
  data = twocities
)
precis(m1, depth =2)

threecities <- filter(Data, (city == "Berlin" | city == "Singapore" | city == "New York"))
                      
m2 <- map2stan(
  alist(
    price ~ dnorm(mu, sigma),
    mu <- alpha + alpha_city[city] + alpha_neighborhood[neighbourhood_group_cleansed],
  alpha ~ dnorm(0, 200),
  alpha_city[city] ~ dnorm(0, sigma_city),
  alpha_neighborhood[neighbourhood_group_cleansed] ~ dnorm(0, sigma_neigh),
  sigma_city ~ dcauchy(0,5),
  sigma_neigh ~ dcauchy(0, 5),
  sigma ~ dcauchy (0,5)
  ),
  data = threecities, chains = 4, warmup = 1000, iter = 4000, cores = 4
)
precis(m2, depth =2)
```
```{R}
#This chunk will be the code to run for a fixed effect model with predictors
mbedbathacomfixed <- map2stan(
  alist(
    price ~ dnorm(mu, sigma),
    mu <- alpha + alpha_city[city] + alpha_neighborhood[neighbourhood_group_cleansed] + 
      bBed * bedrooms + bBath * bathrooms + bAcom * accomodates,
  alpha ~ dnorm(0, 200),
  alpha_city[city] ~ dnorm(0, sigma_city),
  alpha_neighborhood[neighbourhood_group_cleansed] ~ dnorm(0, sigma_neigh),
  sigma_city ~ dcauchy(0,5),
  bBath ~ dnorm(10, 20),
  bBed ~ dnorm(10, 20),
  bAcom ~ dnorm(10, 20)
  sigma_neigh ~ dcauchy(0, 5),
  sigma ~ dcauchy (0,5)
  ),
  data = threecities, chains = 4, warmup = 1000, iter = 4000, cores = 4
)
precis(m2, depth =2)

## This is a model that just does reviews
mreviewsfixed <- map2stan(
  alist(
    price ~ dnorm(mu, sigma),
    mu <- alpha + alpha_city[city] + alpha_neighborhood[neighbourhood_group_cleansed] + 
      bS * host_is_superhost + bR * review_scores_rating,
  alpha ~ dnorm(0, 200),
  alpha_city[city] ~ dnorm(0, sigma_city),
  alpha_neighborhood[neighbourhood_group_cleansed] ~ dnorm(0, sigma_neigh),
  bS ~ dnorm(10, 20),
  bR ~ dnorm(10, 20),
  sigma_city ~ dcauchy(0,5),
  sigma_neigh ~ dcauchy(0, 5),
  sigma ~ dcauchy (0,5)
  ),
  data = threecities, chains = 4, warmup = 1000, iter = 4000, cores = 4
)
precis(m2, depth =2)

#This chunk will be the code to run for a fixed effect model with a predictor for room type as well as all the predictors, bed, bath, and acom
threecities$Entireplace <- ifelse(threecities$room_type == "Entire home/apt", 1, 0)
threecities$Privateroom <- ifelse(threecities$room_type == "Private room", 1, 0)
threecities$Sharedroom <- ifelse(threecities$room_type == "Shared room", 1, 0)
threecities$Hotelroom <- ifelse(threecities$room_type == "Hotel room", 1, 0)
mbedbathfixed <- map2stan(
  alist(
    price ~ dnorm(mu, sigma),
    mu <- alpha + alpha_city[city] + alpha_neighborhood[neighbourhood_group_cleansed] + 
      bBed * bedrooms + bBath * bathrooms + bAcom * accomodates + bPriv * Privateroom +
      bShared * Sharedroom + bHotel * Hotelroom,
  alpha ~ dnorm(0, 200),
  alpha_city[city] ~ dnorm(0, sigma_city),
  alpha_neighborhood[neighbourhood_group_cleansed] ~ dnorm(0, sigma_neigh),
  sigma_city ~ dcauchy(0,5),
  bBath ~ dnorm(10, 20),
  bBed ~ dnorm(10, 20),
  bAcom ~ dnorm(10, 20),
  bPriv ~ dnorm(0, 20),
  bShared ~ dnorm(0, 20),
  bHotel ~ dnorm(0, 20)
  sigma_neigh ~ dcauchy(0, 5),
  sigma ~ dcauchy (0,5)
  ),
  data = threecities, chains = 4, warmup = 1000, iter = 4000, cores = 4
)
## This is a model with all the predictors (except ammentities)
mall <- map2stan(
  alist(
    price ~ dnorm(mu, sigma),
    mu <- alpha + alpha_city[city] + alpha_neighborhood[neighbourhood_group_cleansed] + 
      bBed * bedrooms + bBath * bathrooms + bAcom * accomodates + bPriv * Privateroom +
      bShared * Sharedroom + bHotel * Hotelroom + bS * host_is_superhost + bR *  review_scores_rating,
  alpha ~ dnorm(0, 200),
  alpha_city[city] ~ dnorm(0, sigma_city),
  alpha_neighborhood[neighbourhood_group_cleansed] ~ dnorm(0, sigma_neigh),
  sigma_city ~ dcauchy(0,5),
  bBath ~ dnorm(10, 20),
  bBed ~ dnorm(10, 20),
  bAcom ~ dnorm(10, 20),
  bPriv ~ dnorm(0, 20),
  bShared ~ dnorm(0, 20),
  bHotel ~ dnorm(0, 20),
  bS ~ dnorm(10, 20),
  bR ~ dnorm(10, 20),
  sigma_neigh ~ dcauchy(0, 5),
  sigma ~ dcauchy (0,5)
  ),
  data = threecities, chains = 4, warmup = 1000, iter = 4000, cores = 4
)
  unique(Data$room_type)
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
