---
title: "Visuals"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

```{r}
load("noHierarch.RDS")
load("varyIntercept.RDS")

data <- read.csv("merged.csv")
data <- data[!is.na(data$price),]
```

```{r}
no_vary <- link(noHierarch, data=data.frame(city_factor=c(2, 2, 3, 1, 3, 1, 1, 2, 1, 1, 1, 3, 3, 1, 2, 1, 1, 2, 1, 1, 1, 3), neigh_group_factor=seq(1, 22)), n=2000)
vary <- link(varyIntercept, data=data.frame(city_factor=c(2, 2, 3, 1, 3, 1, 1, 2, 1, 1, 1, 3, 3, 1, 2, 1, 1, 2, 1, 1, 1, 3), neigh_group_factor=seq(1, 22)), n=2000)

no_vary_mean <- apply(no_vary, 2, mean)
vary_mean <- apply(vary, 2, mean)

no_vary_mean <- no_vary_mean[
  #New York
  c(1, 2, 8, 15, 18, 
    #Singapore
    3, 5, 12, 13, 22,
    #Berlin
    4, 6, 7, 9, 10, 11, 14, 16, 17, 19, 20, 21)]

vary_mean <- vary_mean[
  #New York
  c(1, 2, 8, 15, 18, 
    #Singapore
    3, 5, 12, 13, 22,
    #Berlin
    4, 6, 7, 9, 10, 11, 14, 16, 17, 19, 20, 21)]

```
```{r}
plot(1:22, no_vary_mean, xlab = "Neighborhood", ylab = "Estimated mean price", col=rangi2, pch=16, ylim=c(60, 300), main="Intercept Shrinkage in hierarchical model")
points(1:22, vary_mean)
abline(v=c(5.5, 10.5), lty=2)
lines(x=c(0, 5.5), y=rep(coef(noHierarch)["alpha"]+coef(noHierarch)["alpha_city[2]"], 2), col="red")
lines(x=c(5.5, 10.5), y=rep(coef(noHierarch)["alpha"]+coef(noHierarch)["alpha_city[3]"], 2), col="red")
lines(x=c(10.5, 22.5), y=rep(coef(noHierarch)["alpha"]+coef(noHierarch)["alpha_city[1]"], 2), col="red")
text("New York", x=2.75, y=275)
text("Singapore", x=8, y=275)
text("Berlin", x=14, y=275)
legend("topright", c("Non-hierarchical", "Hierarchical"), fill=c(rangi2, "white"))
```

```{r}
plot(data$beds, data$price)
abline(, b=36.25)
```
